Update yamale-validation.yml

diff --git a/.github/workflows/yamale-validation.yml b/.github/workflows/yamale-validation.yml
--- a/.github/workflows/yamale-validation.yml
+++ b/.github/workflows/yamale-validation.yml
@@ -28,8 +28,16 @@ jobs:
       - name: Run validation
         run: |
           find . -type f -name "config.yaml" -not -path "./config.yaml" > file_list.txt
+          validation_failed=false
           while IFS= read -r file; do
             echo "Validating file: $file"
-            yamale -s schema.yaml "$file" || (echo "Validation failed for file: $file"; exit 1)
-          done < file_list.txt > /dev/null
+            if ! yamale -s schema.yaml "$file"; then
+              echo "Validation failed for file: $file"
+              validation_failed=true
+            fi
+          done < file_list.txt
+          if [ "$validation_failed" = true ]; then
+            echo "Validation failed for one or more files."
+            exit 1
+          fi
 
